params:
  epochs: 10
  no_classes: 10
  input_shape: [28, 28]
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000

#bool_params:
#  checkpoint: 1
#  tensorboard: 1
#  early_stopping: 1

artifacts:
  model_dir: artifacts/models
  plot_dir: artifacts/plots
  checkpoint_dir: artifacts/checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs